### PR TITLE
New phony commands

### LINKED ISSUE #3: Add additional commands
- [ ] Add `update` command that will essentially run something like `make gold_vc silver_vc` in the pret repo and then build a .cia file.
- [ ] Add `pretclean` command that will essentially run `make clean` in the pret repo and then build a .cia file.

The names of the command names are not final; open to suggestions. Also open to suggestion of additional commands or functionality.

### PR DESCRIPTION
**Pull request by vulcandth**
*   Renamed `clean` -> `tidy`
*   Renamed `distclean` -> `clean`
*   Added `prettidy`
*   Added `pretclean`
*   Added `update`

Please read the updated `README.md` or `Makefile` comments for info on how they are supposed to work.

Resolves #3

### CODE REVIEW

**Comment by mid-kid** [comment]
Originally I had named it "distclean" because I considered the unpacked romfs part of the source that once unpacked, the user would keep around essentially forever, modifying it to their needs (in terms of manuals, configuration options, logos, whatever). If removing that directory is the preferred workflow when the user wants to rebuild everything, I'd make a directory of files that's copied to the unpacked romfs once unpacked, and can be checked into the repository.

I'd discourage prettidy and pretclean due to how you can simply use -C or "cd" for that.

As for "update", I genuinely think that's not a solution, as this tool is still generating and gather the files automatically (if they don't exist yet), yet making the user responsible for extra steps that when not followed don't raise an error, but can still have subtle to game-breaking consequences.

"make update" is essentially what the user nearly always wants. It's a shame that running "make" on the pokecrystal repo is so slow on windows but it's the only safe behavior. Please make it the default behavior. If you want to avoid it for testing purposes or whatever add a flag like how NODEP=1 is implemented in the gen3 pret repos.

**Comment by vulcandth** [comment]
> Originally I had named it "distclean" because I considered the unpacked romfs part of the source that once unpacked, the user would keep around essentially forever, modifying it to their needs (in terms of manuals, configuration options, logos, whatever). If removing that directory is the preferred workflow when the user wants to rebuild everything, I'd make a directory of files that's copied to the unpacked romfs once unpacked, and can be checked into the repository.

This might become a thing anyways, but that'll be later down the road.

> I'd discourage prettidy and pretclean due to how you can simply use -C or "cd" for that.

Yes; but this simplifies it. They both essentially run two different commands. It was a feature that I personally wanted. I don't think it is going to hurt anything leaving them there. lol

> As for "update", I genuinely think that's not a solution, as this tool is still generating and gather the files automatically (if they don't exist yet), yet making the user responsible for extra steps that when not followed don't raise an error, but can still have subtle to game-breaking consequences.
> 
> "make update" is essentially what the user nearly always wants. It's a shame that running "make" on the pokecrystal repo is so slow on windows but it's the only safe behavior. Please make it the default behavior. If you want to avoid it for testing purposes or whatever add a flag like how NODEP=1 is implemented in the gen3 pret repos.

If we make "update" the default; then i'd probably implement it like this:

*   rename "update" -> "default" and move it up to be the first build target.
*   rename "cia" -> "buildonly" (or something similar)
*   Add a commented out `#.DEFAULT_GOAL := buildonly` to `config.mk.template` with a comment stating that the user may uncomment the line if they wish to change the default behavior to build only and do not ask the pret repo to update `.gbc` and `.patch`

**Comment by vulcandth** [comment]
Final Changelist:

- Renamed `clean` -> `tidy`
- Renamed `distclean` -> `clean`
- Added `prettidy`
- Added `pretclean`
- Added `pretupdate`
- made .PHONY `pretupdate` a order-only perquisite of `.patch` and `.gbc` to tell pret to check for updates prior to building.
- made `../` the default repo location, with the intent to build `poke-cia` inside the pret repo.

**Comment by mid-kid** [comment]
I have never used an order-only phony dependency so please test it. What happens when you edit a file within the pret repo?
Does it cause an update but not rebuild the .cia because the dependency tree is built before execution and a phony order-only dependency doesn't necessarily rebuild a file?
Or does it essentially have the same effect as a normal dependency?

**Comment by vulcandth** [comment]
> I have never used an order-only phony dependency so please test it. What happens when you edit a file within the pret repo? Does it cause an update but not rebuild the .cia because the dependency tree is built before execution and a phony order-only dependency doesn't necessarily rebuild a file? Or does it essentially have the same effect as a normal dependency?

I tested it; it works like its supposed to when a user simply updates a pret file. It will update the `.cia` file as aftewards.

Below is the output when you have already build a `.cia` before.. and now you simply updated a pret `.asm` file and re-run `make` from inside `poke-cia`:

```shell
make -C ../pokedarkgold gold silver gold_vc silver_vc
make[1]: Entering directory '/mnt/c/Users/Matthew/Documents/GitHub/pokedarkgold'

rgbasm -L -Weverything -Wnumeric-string=2 -Wtruncation=1 -D _GOLD -o data/maps/map_data_gold.o data/maps/map_data.asm
rgblink -n pokegold.sym -m pokegold.map -l layout.link -o pokegold.gbc audio_gold.o home_gold.o main_gold.o wram_gold.o data/text/common_gold.o data/maps/map_data_gold.o data/pokemon/egg_moves_gold.o data/pokemon/evos_attacks_gold.o engine/movie/credits_gold.o engine/overworld/events_gold.o gfx/misc_gold.o gfx/sprites_gold.o gfx/tilesets_gold.o data/pokemon/dex_entries_gold.o gfx/pics_gold.o
rgbfix -cjsv -t POKEMON_GLD -i AAUE -k 01 -l 0x33 -m 0x10 -r 3 -p 0 pokegold.gbc
tools/stadium pokegold.gbc
rgbasm -L -Weverything -Wnumeric-string=2 -Wtruncation=1 -D _SILVER -o data/maps/map_data_silver.o data/maps/map_data.asm
rgblink -n pokesilver.sym -m pokesilver.map -l layout.link -o pokesilver.gbc audio_silver.o home_silver.o main_silver.o wram_silver.o data/text/common_silver.o data/maps/map_data_silver.o data/pokemon/egg_moves_silver.o data/pokemon/evos_attacks_silver.o engine/movie/credits_silver.o engine/overworld/events_silver.o gfx/misc_silver.o gfx/sprites_silver.o gfx/tilesets_silver.o data/pokemon/dex_entries_silver.o gfx/pics_silver.o
rgbfix -cjsv -t POKEMON_SLV -i AAXE -k 01 -l 0x33 -m 0x10 -r 3 -p 0 pokesilver.gbc
tools/stadium pokesilver.gbc
rgbasm -L -Weverything -Wnumeric-string=2 -Wtruncation=1 -D _GOLD -D _GOLD_VC -o data/maps/map_data_gold_vc.o data/maps/map_data.asm
rgblink -n pokegold_vc.sym -m pokegold_vc.map -l layout.link -o pokegold_vc.gbc audio_gold_vc.o home_gold_vc.o main_gold_vc.o wram_gold_vc.o data/text/common_gold_vc.o data/maps/map_data_gold_vc.o data/pokemon/egg_moves_gold_vc.o data/pokemon/evos_attacks_gold_vc.o engine/movie/credits_gold_vc.o engine/overworld/events_gold_vc.o gfx/misc_gold_vc.o gfx/sprites_gold_vc.o gfx/tilesets_gold_vc.o data/pokemon/dex_entries_gold_vc.o gfx/pics_gold_vc.o
rgbfix -cjsv -t POKEMON_GLD -i AAUE -k 01 -l 0x33 -m 0x10 -r 3 -p 0 pokegold_vc.gbc
tools/stadium pokegold_vc.gbc
tools/make_patch pokegold_vc.sym vc/pokegold.constants.sym pokegold_vc.gbc pokegold.gbc vc/pokegold.patch.template pokegold.patch
rgbasm -L -Weverything -Wnumeric-string=2 -Wtruncation=1 -D _SILVER -D _GOLD_VC -o data/maps/map_data_silver_vc.o data/maps/map_data.asm
rgblink -n pokesilver_vc.sym -m pokesilver_vc.map -l layout.link -o pokesilver_vc.gbc audio_silver_vc.o home_silver_vc.o main_silver_vc.o wram_silver_vc.o data/text/common_silver_vc.o data/maps/map_data_silver_vc.o data/pokemon/egg_moves_silver_vc.o data/pokemon/evos_attacks_silver_vc.o engine/movie/credits_silver_vc.o engine/overworld/events_silver_vc.o gfx/misc_silver_vc.o gfx/sprites_silver_vc.o gfx/tilesets_silver_vc.o data/pokemon/dex_entries_silver_vc.o gfx/pics_silver_vc.o
rgbfix -cjsv -t POKEMON_SLV -i AAXE -k 01 -l 0x33 -m 0x10 -r 3 -p 0 pokesilver_vc.gbc
tools/stadium pokesilver_vc.gbc
tools/make_patch pokesilver_vc.sym vc/pokesilver.constants.sym pokesilver_vc.gbc pokesilver.gbc vc/pokesilver.patch.template pokesilver.patch
make[1]: Leaving directory '/mnt/c/Users/Matthew/Documents/GitHub/pokedarkgold'
mkdir -p pokegold/romfs/rom
cp -T ../pokedarkgold/pokegold.gbc pokegold/romfs/rom/pokegold
env -C pokegold/ makerom -f cxi -o ../pokegold.game.cxi -rsf ../game.rsf -exheader exheader.bin -logo logo.lz -plainrgn plain.bin -code exefs/code.bin -icon exefs/icon.bin -banner exefs/banner.bin
env -C pokegold \
    makerom -f cfa -o ../pokegold.manual.cfa -rsf ../manual.rsf
makerom -f cia -o pokegold.cia -content pokegold.game.cxi:0:0 -content pokegold.manual.cfa:1:1
mkdir -p pokesilver/romfs
cp -T ../pokedarkgold/pokesilver.patch pokesilver/romfs/pokesilver.patch
mkdir -p pokesilver/romfs/rom
cp -T ../pokedarkgold/pokesilver.gbc pokesilver/romfs/rom/pokesilver
env -C pokesilver/ makerom -f cxi -o ../pokesilver.game.cxi -rsf ../game.rsf -exheader exheader.bin -logo logo.lz -plainrgn plain.bin -code exefs/code.bin -icon exefs/icon.bin -banner exefs/banner.bin
env -C pokesilver \
    makerom -f cfa -o ../pokesilver.manual.cfa -rsf ../manual.rsf
makerom -f cia -o pokesilver.cia -content pokesilver.game.cxi:0:0 -content pokesilver.manual.cfa:1:1
rm pokegold.manual.cfa pokesilver.manual.cfa
```

**Comment by mid-kid** [comment]
Nice. Is that any different from when it's a regular dependency? Just curious.

**Comment by mid-kid** [comment]
Oh and what about `make -j 8` when used on a clean repo? Won't that spawn pokecrystal's `make` multiple times for the same thing?
(sorry for being so picky lol...)

**Pull request merged**
